In [6]:
!pwd

/Users/shihosato/src/github.com/twinkle13531/master_degree/202012/Summary


In [7]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [8]:
import sys, os
sys.path.append(os.path.join('..', 'Random'))
sys.path.append(os.path.join('..', 'SA'))
sys.path.append(os.path.join('..', 'QA'))
sys.path.append(os.path.join('..', '4ti2', 'functions'))

In [9]:
import QA_DwaveSampler_AutoEmbedding as qda
import random_exact_test_functions as ret
import SA_exact_test_functions as net
import zsolve_t1 as zt
import pandas as pd
import numpy as np
import time
import matplotlib.pyplot as plt
import statistics
import math

In [10]:
time_dic = {}

In [11]:
y_dic = {'total_y_num':{}, 'mean_occurrence':{}, 'valid_y_num':{}}

In [12]:
per_time_dic = {}

In [13]:
mean_broken_chain_proportion = {}#only QA

In [29]:
p_dic = {}

In [14]:
chain_strength_dic = {20:10, 25:15, 30:20, 35:20, 40:30}

In [15]:
bit_list = [20, 25, 30, 35, 40]
num_list = [0, 1, 2, 3, 4]

## QA
計算時間の制約があるので一気に、まとめて計算する。

In [102]:
n, num_reads = 10, 1000

In [103]:
time_dic['QA'] = {}
y_dic['total_y_num']['QA'] = {}
y_dic['mean_occurrence']['QA'] = {}
y_dic['valid_y_num']['QA'] = {}
per_time_dic['QA'] = {}
p_dic['QA'] = {}

In [105]:
for bit in [20, 25, 30, 35, 40]:
    time_dic['QA'][bit] = {}
    y_dic['total_y_num']['QA'][bit] = {}
    y_dic['mean_occurrence']['QA'][bit] = {}
    y_dic['valid_y_num']['QA'][bit] = {}
    per_time_dic['QA'][bit] = {}
    mean_broken_chain_proportion[bit] = {}
    p_dic['QA'][bit] = {}
    chain_strength = chain_strength_dic[bit]
    
    for num in [0, 1, 2, 3, 4]:
        path = '../input/ost{}_{}.csv'.format(bit, num)
        df = pd.read_csv(path, sep=',')
        bqm = qda.make_Hamiltonian(df)
        
        qqda = qda.QA_DSampler_AEmbedding(df, bqm, n, num_reads, chain_strength)
        valid_y_info_dic, calculation_time = qqda.find_valid_y_time_ntimes()
        
        if len(valid_y_info_dic) > 0:
            occurrence_list = [valid_y_info[0] for valid_y_info in list(valid_y_info_dic.values())]
            broken_list = [valid_y_info[1] for valid_y_info in list(valid_y_info_dic.values())]

            time_dic['QA'][bit][num] = calculation_time
            y_dic['total_y_num']['QA'][bit][num] = sum(occurrence_list)
            y_dic['mean_occurrence']['QA'][bit][num] = statistics.mean(occurrence_list)
            y_dic['valid_y_num']['QA'][bit][num] = len(valid_y_info_dic)
            per_time_dic['QA'][bit][num] = calculation_time / sum(occurrence_list)
            mean_broken_chain_proportion[bit][num] = statistics.mean(broken_list)
            p_dic['QA'][bit][num] = qqda.p_value(valid_y_info_dic)

            print('{}_{} finish'.format(bit, num))

20_0 finish
20_1 finish
20_2 finish
20_3 finish
20_4 finish
25_0 finish
25_1 finish
25_2 finish
25_3 finish
25_4 finish
30_0 finish
30_1 finish
30_2 finish
30_3 finish
30_4 finish
35_0 finish
35_1 finish
35_2 finish
35_3 finish
35_4 finish
40_0 finish
40_1 finish


OSError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

In [106]:
for bit in [40]:
    time_dic['QA'][bit] = {}
    y_dic['total_y_num']['QA'][bit] = {}
    y_dic['mean_occurrence']['QA'][bit] = {}
    y_dic['valid_y_num']['QA'][bit] = {}
    per_time_dic['QA'][bit] = {}
    mean_broken_chain_proportion[bit] = {}
    p_dic['QA'][bit] = {}
    chain_strength = chain_strength_dic[bit]
    
    for num in [2, 3, 4]:
        path = '../input/ost{}_{}.csv'.format(bit, num)
        df = pd.read_csv(path, sep=',')
        bqm = qda.make_Hamiltonian(df)
        
        qqda = qda.QA_DSampler_AEmbedding(df, bqm, n, num_reads, chain_strength)
        valid_y_info_dic, calculation_time = qqda.find_valid_y_time_ntimes()
        
        if len(valid_y_info_dic) > 0:
            occurrence_list = [valid_y_info[0] for valid_y_info in list(valid_y_info_dic.values())]
            broken_list = [valid_y_info[1] for valid_y_info in list(valid_y_info_dic.values())]

            time_dic['QA'][bit][num] = calculation_time
            y_dic['total_y_num']['QA'][bit][num] = sum(occurrence_list)
            y_dic['mean_occurrence']['QA'][bit][num] = statistics.mean(occurrence_list)
            y_dic['valid_y_num']['QA'][bit][num] = len(valid_y_info_dic)
            per_time_dic['QA'][bit][num] = calculation_time / sum(occurrence_list)
            mean_broken_chain_proportion[bit][num] = statistics.mean(broken_list)
            p_dic['QA'][bit][num] = qqda.p_value(valid_y_info_dic)

            print('{}_{} finish'.format(bit, num))

40_2 finish
40_3 finish
40_4 finish


In [107]:
time_dic['QA']

{20: {0: 10100.302781969025,
  1: 7083.695348590287,
  2: 6783.629804111206,
  3: 7001.765937281618,
  4: 7069.230774524955},
 25: {0: 7721.309690435541,
  1: 7743.950730977868,
  2: 7800.795792068823,
  3: 7677.552796172866,
  4: 7454.260442603152},
 30: {0: 8788.167812805043,
  1: 7869.4621739470385,
  2: 7924.064222289954,
  3: 7972.860044433406,
  4: 8421.326937390904},
 35: {0: 13453.390574883151,
  1: 9065.021765900708,
  2: 9719.771954993652,
  3: 9453.069209528536,
  4: 8947.405568076443},
 40: {2: 16109.036972949694, 3: 9023.643173886478, 4: 13011.280886601266}}

In [108]:
y_dic['total_y_num']['QA']

{20: {0: 1135, 1: 169, 2: 582, 3: 212, 4: 72},
 25: {0: 100, 1: 270, 2: 32, 3: 8, 4: 120},
 30: {0: 12, 1: 10, 2: 35, 3: 13, 4: 128},
 35: {0: 6, 1: 18, 2: 22, 3: 12, 4: 16},
 40: {2: 12, 3: 6, 4: 5}}

In [109]:
y_dic['mean_occurrence']['QA']

{20: {0: 2, 1: 1, 2: 1, 3: 1, 4: 1},
 25: {0: 1, 1: 1, 2: 1, 3: 1, 4: 1},
 30: {0: 1, 1: 1, 2: 1, 3: 1, 4: 1},
 35: {0: 1, 1: 1, 2: 1, 3: 1, 4: 1},
 40: {2: 1, 3: 1, 4: 1}}

In [110]:
y_dic['valid_y_num']['QA']

{20: {0: 508, 1: 154, 2: 415, 3: 196, 4: 62},
 25: {0: 100, 1: 270, 2: 32, 3: 8, 4: 120},
 30: {0: 12, 1: 10, 2: 35, 3: 13, 4: 128},
 35: {0: 6, 1: 18, 2: 22, 3: 12, 4: 16},
 40: {2: 12, 3: 6, 4: 5}}

In [111]:
per_time_dic['QA']

{20: {0: 8.898945182351564,
  1: 41.91535709225022,
  2: 11.655721312905852,
  3: 33.02719781736612,
  4: 98.18376075729105},
 25: {0: 77.21309690435541,
  1: 28.681299003621735,
  2: 243.77486850215072,
  3: 959.6940995216082,
  4: 62.11883702169293},
 30: {0: 732.3473177337536,
  1: 786.9462173947038,
  2: 226.40183492257012,
  3: 613.2969264948774,
  4: 65.79161669836644},
 35: {0: 2242.231762480525,
  1: 503.61232032781714,
  2: 441.8078161360751,
  3: 787.7557674607114,
  4: 559.2128480047777},
 40: {2: 1342.4197477458079, 3: 1503.9405289810795, 4: 2602.2561773202533}}

In [112]:
p_dic['QA']

{20: {0: 0.3169291338582677,
  1: 0.12987012987012986,
  2: 0.2819277108433735,
  3: 0.22448979591836735,
  4: 0.46774193548387094},
 25: {0: 0.14, 1: 0.0962962962962963, 2: 0.1875, 3: 0.0, 4: 0.2},
 30: {0: 0.08333333333333333,
  1: 0.1,
  2: 0.3142857142857143,
  3: 0.07692307692307693,
  4: 0.0625},
 35: {0: 0.16666666666666666, 1: 0.0, 2: 0.0, 3: 0.0, 4: 0.3125},
 40: {2: 0.0, 3: 0.0, 4: 0.0}}

In [113]:
QA_mean_time_list = []
QA_std_time_list = []
for bit in bit_list:
    time_list = list(per_time_dic['QA'][bit].values())
    QA_mean_time_list.append(statistics.mean(time_list))
    QA_std_time_list.append(statistics.pstdev(time_list))
    
QA_mean_time = np.array(QA_mean_time_list)
QA_std_time = np.array(QA_std_time_list)

In [114]:
QA_mean_time

array([  38.73619643,  274.29644019,  484.95678265,  906.92410288,
       1816.20548468])

In [115]:
QA_std_time

array([ 32.25004287, 350.68204825, 286.85222168, 677.81181885,
       559.71957815])

## Random

In [68]:
num_reads = 10000

In [69]:
time_dic['random'] = {}
y_dic['total_y_num']['random'] = {}
y_dic['mean_occurrence']['random'] = {}
y_dic['valid_y_num']['random'] = {}
per_time_dic['random'] = {}
p_dic['random'] = {}

In [70]:
for bit in bit_list:
    time_dic['random'][bit] = {}
    y_dic['total_y_num']['random'][bit] = {}
    y_dic['mean_occurrence']['random'][bit] = {}
    y_dic['valid_y_num']['random'][bit] = {}
    per_time_dic['random'][bit] = {}
    p_dic['random'][bit] = {}
    
    for num in num_list:
        df_path = '../input/ost{}_{}.csv'.format(bit, num)
        df = pd.read_csv(df_path, sep=',')
        t_list = ret.calc_marginals(df)
        valid_y_dic, calculation_time = ret.find_valid_y(df, num_reads)
        
        if len(valid_y_dic) > 0:
            rm = ret.Random_method(df, valid_y_dic, num_reads, t_list)
            
            mean_occurrence_list = [i for i in list(valid_y_dic.values())]
            
            time_dic['random'][bit][num] = calculation_time
            y_dic['total_y_num']['random'][bit][num] = sum(mean_occurrence_list)
            y_dic['mean_occurrence']['random'][bit][num] = statistics.mean(mean_occurrence_list)
            y_dic['valid_y_num']['random'][bit][num] = len(valid_y_dic)
            per_time_dic['random'][bit][num] = calculation_time / len(valid_y_dic)
            p_dic['random'][bit][num] = rm.p_value()

In [71]:
time_dic['random']

{20: {0: 0.17365789413452148,
  1: 0.1555769443511963,
  2: 0.04897308349609375,
  3: 0.17087912559509277,
  4: 0.1624460220336914},
 25: {0: 0.06797575950622559,
  1: 0.09294724464416504,
  2: 0.12764787673950195,
  4: 0.07495784759521484},
 30: {1: 0.07776403427124023, 2: 0.12283015251159668, 4: 0.05878782272338867},
 35: {1: 0.09458684921264648,
  2: 0.14945006370544434,
  3: 0.10146880149841309,
  4: 0.08700895309448242},
 40: {1: 0.08776688575744629}}

In [72]:
y_dic['total_y_num']['random']

{20: {0: 146, 1: 10, 2: 6, 3: 26, 4: 5},
 25: {0: 3, 1: 31, 2: 5, 4: 6},
 30: {1: 1, 2: 4, 4: 8},
 35: {1: 5, 2: 3, 3: 1, 4: 4},
 40: {1: 1}}

In [73]:
y_dic['mean_occurrence']['random']

{20: {0: 1.006896551724138, 1: 1, 2: 1, 3: 1, 4: 1},
 25: {0: 1, 1: 1, 2: 1, 4: 1},
 30: {1: 1, 2: 1, 4: 1},
 35: {1: 1, 2: 1, 3: 1, 4: 1},
 40: {1: 1}}

In [74]:
y_dic['valid_y_num']['random']

{20: {0: 145, 1: 10, 2: 6, 3: 26, 4: 5},
 25: {0: 3, 1: 31, 2: 5, 4: 6},
 30: {1: 1, 2: 4, 4: 8},
 35: {1: 5, 2: 3, 3: 1, 4: 4},
 40: {1: 1}}

In [75]:
per_time_dic['random']

{20: {0: 0.0011976406492035965,
  1: 0.015557694435119628,
  2: 0.008162180582682291,
  3: 0.006572274061349722,
  4: 0.03248920440673828},
 25: {0: 0.022658586502075195,
  1: 0.0029982982143279043,
  2: 0.02552957534790039,
  4: 0.012492974599202475},
 30: {1: 0.07776403427124023, 2: 0.03070753812789917, 4: 0.007348477840423584},
 35: {1: 0.018917369842529296,
  2: 0.04981668790181478,
  3: 0.10146880149841309,
  4: 0.021752238273620605},
 40: {1: 0.08776688575744629}}

In [76]:
p_dic['random']

{20: {0: 0.1793103448275862,
  1: 0.1,
  2: 0.16666666666666666,
  3: 0.15384615384615385,
  4: 0.6},
 25: {0: 0.3333333333333333, 1: 0.12903225806451613, 2: 0.4, 4: 0.0},
 30: {1: 0.0, 2: 0.25, 4: 0.125},
 35: {1: 0.0, 2: 0.0, 3: 0.0, 4: 0.25},
 40: {1: 0.0}}

In [77]:
random_mean_time_list = []
random_std_time_list = []
for bit in bit_list:
    time_list = list(per_time_dic['random'][bit].values())
    random_mean_time_list.append(statistics.mean(time_list))
    random_std_time_list.append(statistics.pstdev(time_list))
    
random_mean_time = np.array(random_mean_time_list)
random_std_time = np.array(random_std_time_list)

In [78]:
random_mean_time

array([0.14230661, 0.09088218, 0.08646067, 0.10812867, 0.08776689])

In [79]:
random_std_time

array([0.04710018, 0.02309908, 0.02685862, 0.02439895, 0.        ])

## SA

In [129]:
num_reads = 10000

In [130]:
time_dic['SA'] = {}
y_dic['total_y_num']['SA'] = {}
y_dic['mean_occurrence']['SA'] = {}
y_dic['valid_y_num']['SA'] = {}
per_time_dic['SA'] = {}
p_dic['SA'] = {}

In [131]:
for bit in bit_list:
    time_dic['SA'][bit] = {}
    y_dic['total_y_num']['SA'][bit] = {}
    y_dic['mean_occurrence']['SA'][bit] = {}
    y_dic['valid_y_num']['SA'][bit] = {}
    per_time_dic['SA'][bit] = {}
    p_dic['SA'][bit] = {}
    
    for num in num_list:
        
        path = '../input/ost{}_{}.csv'.format(bit, num)
        df = pd.read_csv(path, sep=',')
        
        time_0 = time.time()
        res = net.make_res_data(df, num_reads)
        valid_y_info_dic = net.find_valid_y(res)
        time_1 = time.time()
        calculation_time = time_1 - time_0
        
        if len(valid_y_info_dic) > 0:
            rvd = net.SA_res_valid_dic(df, res, valid_y_info_dic, num_reads)
            
            time_dic['SA'][bit][num] = calculation_time
            y_dic['total_y_num']['SA'][bit][num] = sum(mean_occurrence_list)
            y_dic['mean_occurrence']['SA'][bit][num] = statistics.mean(mean_occurrence_list)
            y_dic['valid_y_num']['SA'][bit][num] = len(valid_y_info_dic)
            per_time_dic['SA'][bit][num] = calculation_time / len(valid_y_info_dic)
            p_dic['SA'][bit][num] = rvd.calc_p_value()
            
            print('{}_{} finish'.format(bit, num))

20_0 finish
20_1 finish
20_2 finish
20_3 finish
20_4 finish
25_0 finish
25_1 finish
25_2 finish
25_3 finish
25_4 finish
30_0 finish
30_1 finish
30_2 finish
30_3 finish
30_4 finish
35_0 finish
35_1 finish
35_2 finish
35_3 finish
35_4 finish
40_0 finish
40_1 finish
40_2 finish
40_3 finish
40_4 finish


In [132]:
time_dic['SA']

{20: {0: 9.192142009735107,
  1: 5.5356810092926025,
  2: 5.4850780963897705,
  3: 5.849268436431885,
  4: 5.062978029251099},
 25: {0: 11.261059045791626,
  1: 13.47816276550293,
  2: 10.009632110595703,
  3: 7.092028856277466,
  4: 11.799193143844604},
 30: {0: 15.510584115982056,
  1: 14.910096883773804,
  2: 15.314063787460327,
  3: 15.20064115524292,
  4: 15.242308139801025},
 35: {0: 18.32283902168274,
  1: 19.380826711654663,
  2: 18.023081064224243,
  3: 17.786306858062744,
  4: 17.07033920288086},
 40: {0: 21.340198278427124,
  1: 20.588493824005127,
  2: 21.43675184249878,
  3: 20.29060697555542,
  4: 21.051637887954712}}

In [133]:
y_dic['total_y_num']['SA']

{20: {0: 1, 1: 1, 2: 1, 3: 1, 4: 1},
 25: {0: 1, 1: 1, 2: 1, 3: 1, 4: 1},
 30: {0: 1, 1: 1, 2: 1, 3: 1, 4: 1},
 35: {0: 1, 1: 1, 2: 1, 3: 1, 4: 1},
 40: {0: 1, 1: 1, 2: 1, 3: 1, 4: 1}}

In [134]:
y_dic['mean_occurrence']['SA']

{20: {0: 1, 1: 1, 2: 1, 3: 1, 4: 1},
 25: {0: 1, 1: 1, 2: 1, 3: 1, 4: 1},
 30: {0: 1, 1: 1, 2: 1, 3: 1, 4: 1},
 35: {0: 1, 1: 1, 2: 1, 3: 1, 4: 1},
 40: {0: 1, 1: 1, 2: 1, 3: 1, 4: 1}}

In [135]:
y_dic['valid_y_num']['SA']

{20: {0: 7351, 1: 1361, 2: 1635, 3: 2346, 4: 260},
 25: {0: 6764, 1: 9283, 2: 6919, 3: 1370, 4: 7842},
 30: {0: 9009, 1: 8531, 2: 9820, 3: 8886, 4: 9837},
 35: {0: 9525, 1: 9782, 2: 9830, 3: 9534, 4: 9435},
 40: {0: 9663, 1: 9797, 2: 9687, 3: 9571, 4: 9561}}

In [136]:
per_time_dic['SA']

{20: {0: 0.0012504614351428523,
  1: 0.00406736297523336,
  2: 0.003354787826538086,
  3: 0.0024932943036794055,
  4: 0.019472992420196532},
 25: {0: 0.0016648520174144922,
  1: 0.0014519188587205569,
  2: 0.001446687687613196,
  3: 0.005176663398742676,
  4: 0.0015046152950579704},
 30: {0: 0.0017216765585505668,
  1: 0.0017477548802923226,
  2: 0.0015594769640998297,
  3: 0.0017106280840921584,
  4: 0.0015494874595711116},
 35: {0: 0.0019236576400716787,
  1: 0.0019812744542685203,
  2: 0.0018334772191479392,
  3: 0.0018655660644076718,
  4: 0.0018092569372422744},
 40: {0: 0.002208444404266493,
  1: 0.0021015100361340337,
  2: 0.0022129402129140887,
  3: 0.0021200090874052262,
  4: 0.0022018238560772632}}

In [137]:
p_dic['SA']

{20: {0: 0.2274520473404979,
  1: 0.21528288023512124,
  2: 0.3333333333333333,
  3: 0.2638533674339301,
  4: 0.4153846153846154},
 25: {0: 0.0833826138379657,
  1: 0.06409565873101368,
  2: 0.15074432721491546,
  3: 0.15766423357664233,
  4: 0.25108390716653917},
 30: {0: 0.041736041736041736,
  1: 0.3085218614464893,
  2: 0.20631364562118126,
  3: 0.10600945307224847,
  4: 0.06567042797600894},
 35: {0: 0.06236220472440945,
  1: 0.04763851973011654,
  2: 0.01261444557477111,
  3: 0.07300188797986155,
  4: 0.15029146793852677},
 40: {0: 0.04284383731760323,
  1: 0.05471062570174543,
  2: 0.0322081139671725,
  3: 0.06634625430989448,
  4: 0.026880033469302376}}

In [138]:
SA_mean_time_list = []
SA_std_time_list = []
for bit in bit_list:
    time_list = list(per_time_dic['SA'][bit].values())
    SA_mean_time_list.append(statistics.mean(time_list))
    SA_std_time_list.append(statistics.pstdev(time_list))
    
SA_mean_time = np.array(SA_mean_time_list)
SA_std_time = np.array(SA_std_time_list)

In [139]:
SA_mean_time

array([0.00612778, 0.00224895, 0.0016578 , 0.00188265, 0.00216895])

In [140]:
SA_std_time

array([6.73835620e-03, 1.46598730e-03, 8.52782826e-05, 6.24576246e-05,
       4.79979140e-05])

## exhaustive enumeration

In [116]:
enu_time_dic = {}
enu_time_dic[20] = [4.84, 0.02, 0.23, 0.38, 0.65]
enu_time_dic[25] = [5.47, 2894.31, 4.19, 0.23, 15.37]
enu_time_dic[30] = [120017.00, 105.15, 12792.04, 725.79]

In [ ]:
#enu_time_dic[30] = [120017.00, 105.15, 12792.04, 725.79, ,]
#enu_time_dic[35] = [, , , , , ]
#enu_time_dic[40] = [64667.50, , , , ,]

In [117]:
time_dic['enumeration'] = {}
y_dic['valid_y_num']['enumeration'] = {}
per_time_dic['enumeration'] = {}
p_dic['enumeration'] = {}

In [118]:
for bit in [20, 25]:
    time_dic['enumeration'][bit] = {}
    y_dic['valid_y_num']['enumeration'][bit] = {}
    per_time_dic['enumeration'][bit] = {}
    p_dic['enumeration'][bit] = {}
    
    for num in [0, 1, 2, 3, 4]:
        
        path = '../input/ost{}_{}.csv'.format(bit, num)
        df = pd.read_csv(path, sep=',')
        
        zinhom_path = '../4ti2/{}bit/{}/{}bit_{}.zinhom'.format(bit, num, bit, num)
        zinhom_num, zinhom_list = zt.make_result_list(zinhom_path)
        
        if zinhom_num > 0:
            zrs = zt.zsolve_result_summerize(df, zinhom_list)
            
            time_dic['enumeration'][bit][num] = enu_time_dic[bit][num]
            y_dic['valid_y_num']['enumeration'][bit][num] = zinhom_num
            per_time_dic['enumeration'][bit][num] = enu_time_dic[bit][num] / zinhom_num
            p_dic['enumeration'][bit][num] = zrs.calucurate_p()

            print('{}_{} finish'.format(bit, num))

20_0 finish
20_1 finish
20_2 finish
20_3 finish
20_4 finish
25_0 finish
25_1 finish
25_2 finish
25_3 finish
25_4 finish


In [119]:
for bit in [30]:
    time_dic['enumeration'][bit] = {}
    y_dic['valid_y_num']['enumeration'][bit] = {}
    per_time_dic['enumeration'][bit] = {}
    p_dic['enumeration'][bit] = {}
    
    for num in [0, 1, 2, 3]:
        
        path = '../input/ost{}_{}.csv'.format(bit, num)
        df = pd.read_csv(path, sep=',')
        
        zinhom_path = '../4ti2/{}bit/{}/{}bit_{}.zinhom'.format(bit, num, bit, num)
        zinhom_num, zinhom_list = zt.make_result_list(zinhom_path)
        
        if zinhom_num > 0:
            zrs = zt.zsolve_result_summerize(df, zinhom_list)
            
            time_dic['enumeration'][bit][num] = enu_time_dic[bit][num]
            y_dic['valid_y_num']['enumeration'][bit][num] = zinhom_num
            per_time_dic['enumeration'][bit][num] = enu_time_dic[bit][num] / zinhom_num
            p_dic['enumeration'][bit][num] = zrs.calucurate_p()

            print('{}_{} finish'.format(bit, num))

30_0 finish
30_1 finish
30_2 finish
30_3 finish


In [120]:
time_dic['enumeration']

{20: {0: 4.84, 1: 0.02, 2: 0.23, 3: 0.38, 4: 0.65},
 25: {0: 5.47, 1: 2894.31, 2: 4.19, 3: 0.23, 4: 15.37},
 30: {0: 120017.0, 1: 105.15, 2: 12792.04, 3: 725.79}}

In [122]:
y_dic['valid_y_num']['enumeration']

{20: {0: 16464, 1: 1365, 2: 1638, 3: 2397, 4: 260},
 25: {0: 12600, 1: 89796, 2: 14700, 3: 1372, 4: 21000},
 30: {0: 58296, 1: 57159, 2: 429660, 3: 127440}}

In [123]:
per_time_dic['enumeration']

{20: {0: 0.00029397473275024293,
  1: 1.4652014652014653e-05,
  2: 0.00014041514041514042,
  3: 0.00015853149770546517,
  4: 0.0025},
 25: {0: 0.0004341269841269841,
  1: 0.03223205933449151,
  2: 0.0002850340136054422,
  3: 0.00016763848396501459,
  4: 0.0007319047619047618},
 30: {0: 2.058751886921916,
  1: 0.0018396053114995016,
  2: 0.029772471256342227,
  3: 0.00569515065913371}}

In [124]:
p_dic['enumeration']

{20: {0: 0.22959183673469388,
  1: 0.2153846153846154,
  2: 0.3333333333333333,
  3: 0.2640801001251564,
  4: 0.4153846153846154},
 25: {0: 0.08333333333333333,
  1: 0.0608044901777362,
  2: 0.15306122448979592,
  3: 0.15743440233236153,
  4: 0.248},
 30: {0: 0.04459997255386304,
  1: 0.31648559282002836,
  2: 0.20353302611367127,
  3: 0.11007532956685499}}

In [126]:
enu_mean_time_list = []
enu_std_time_list = []
for bit in [20,  25]:
    time_list = list(per_time_dic['enumeration'][bit].values())
    enu_mean_time_list.append(statistics.mean(time_list))
    enu_std_time_list.append(statistics.pstdev(time_list))
    
enu_mean_time = np.array(enu_mean_time_list)
enu_std_time = np.array(enu_std_time_list)

In [127]:
enu_mean_time

array([0.00062151, 0.00677015])

In [128]:
enu_std_time

array([0.00094341, 0.01273235])