- [hsnf](https://github.com/lan496/hsnf):エルミート標準形

In [1]:
import sys
print(sys.path)

['/Users/shihosato/src/github.com/twinkle13531/master_degree/202010/scripts', '/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python38.zip', '/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8', '/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/lib-dynload', '', '/usr/local/lib/python3.8/site-packages', '/usr/local/lib/python3.8/site-packages/hsnf-0.2.0-py3.8.egg', '/usr/local/lib/python3.8/site-packages/numpy-1.19.2-py3.8-macosx-10.15-x86_64.egg', '/usr/local/lib/python3.8/site-packages/IPython/extensions', '/Users/shihosato/.ipython']


In [2]:
from hsnf import column_style_hermite_normal_form

In [3]:
from hsnf import row_style_hermite_normal_form, column_style_hermite_normal_form

In [16]:
M = np.array([
    [-6, 111, -36, 6],
    [5, -672, 210, 74],
    [0, -255, 81, 24],
])

In [21]:
H, L = row_style_hermite_normal_form(M)#上三角

In [22]:
H 

array([[     1,      0,    420,  -2522],
       [     0,      3,   1809, -10860],
       [     0,      0,   2079, -12474]])

In [23]:
np.dot(L, M)  # equal to H, upper triangular

array([[     1,      0,    420,  -2522],
       [     0,      3,   1809, -10860],
       [     0,      0,   2079, -12474]])

In [24]:
np.abs(np.linalg.det(L))  # equal to 1

0.9999999999990337

In [17]:
H, R = column_style_hermite_normal_form(M)#下三角

In [18]:
H

array([[   3,    0,    0,    0],
       [   0,    1,    0,    0],
       [1185,  474, 2079,    0]])

In [19]:
np.dot(M, R)  # equal to H, lower-triangular

array([[   3,    0,    0,    0],
       [   0,    1,    0,    0],
       [1185,  474, 2079,    0]])

In [20]:
np.abs(np.linalg.det(R))  # equal to 1

0.9999999999975868

In [25]:
m = ost46['SEX']

In [26]:
h, l = row_style_hermite_normal_form(m)#上三角

ValueError: matrix representation must be 2d