In [5]:
!pip3 install sympy

    100% |################################| 5.8MB 251kB/s ta 0:00:011  3% |#                               | 194kB 3.4MB/s eta 0:00:02
    100% |################################| 522kB 3.1MB/s eta 0:00:01
  Running setup.py bdist_wheel for mpmath ... done
  Stored in directory: /root/.cache/pip/wheels/63/9d/8e/37c3f6506ed3f152733a699e92d8e0c9f5e5f01dea262f80ad
Successfully built mpmath


In [13]:
#!pip3 install desr #error

/bin/sh: 1: setup.py: not found


In [15]:
import sympy
from desr import matrix_normal_forms

ModuleNotFoundError: No module named 'desr'

In [8]:
A = sympy.Matrix([[8, 2, 15, 9, 11],[6, 0, 6, 2, 3]])
h, v = normal_hnf_col(A)

NameError: name 'normal_hnf_col' is not defined

In [ ]:
h

In [ ]:
v

In [ ]:
(A * v) == h

In [10]:
#!pip3 install hsnf

In [1]:
import numpy as np
from hsnf import smith_normal_form
from hsnf import row_style_hermite_normal_form, column_style_hermite_normal_form

ModuleNotFoundError: No module named 'hsnf'

In [ ]:


M = np.array([
    [-6, 111, -36, 6],
    [5, -672, 210, 74],
    [0, -255, 81, 24],
])

# smith normal form
D, L, R = smith_normal_form(M)
"""
D = array([
  [   1    0    0    0]
  [   0    3    0    0]
  [   0    0 2079    0]])
"""
np.dot(L, np.dot(M, R))  # equal to D, diagonal
np.abs(np.linalg.det(L))  # equal to 1
np.abs(np.linalg.det(R))  # equal to 1

# row-style hermite normal form
H, L = row_style_hermite_normal_form(M)
"""
H = array([
  [     1      0    420  -2522]
  [     0      3   1809 -10860]
  [     0      0   2079 -12474]])
"""
np.dot(L, M)  # equal to H, upper triangular
np.abs(np.linalg.det(L))  # equal to 1

# column-style hermite normal form
H, R = column_style_hermite_normal_form(M)
"""
H = array([
  [   3    0    0    0]
  [   0    1    0    0]
  [1185  474 2079    0]])
"""
np.dot(M, R)  # equal to H, lower-triangular
np.abs(np.linalg.det(R))  # equal to 1