In [3]:
!pip3 install dwave-neal

    100% |################################| 399kB 2.3MB/s ta 0:00:01
    100% |################################| 4.7MB 331kB/s ta 0:00:011


In [1]:
import numpy as np
import neal

In [2]:
dim = 8

In [3]:
w1 = np.ones(dim)
w2 = np.array([0,1,0,1,0,1,0,1])

x1+..+x8 = 0　と　x2+x4+x6+x8=0からサンプルを発生

In [6]:
w1

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
w2

array([0, 1, 0, 1, 0, 1, 0, 1])

In [11]:
JJ1 = np.zeros((dim,dim))
for i in range(dim):
    for j in range(dim):
        JJ1[i,j] = w1[i]*w1[j] + w2[i]*w2[j]
        #print(w1[i]*w1[j])
        #print(w2[i]*w2[j])
        #print(JJ1[i,j])
        #print('---------------')

In [6]:
print(JJ1)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 2. 1. 2. 1. 2. 1. 2.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 2. 1. 2. 1. 2. 1. 2.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 2. 1. 2. 1. 2. 1. 2.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 2. 1. 2. 1. 2. 1. 2.]]


In [12]:
J = {}
h = {}
for i in range(dim):
    h[i] = 0
    for j in range(i,dim):#0-7, 1-7, ..., 7
        print(i, j)
        J[i,j] = JJ1[i,j]

0 0
0 1
0 2
0 3
0 4
0 5
0 6
0 7
1 1
1 2
1 3
1 4
1 5
1 6
1 7
2 2
2 3
2 4
2 5
2 6
2 7
3 3
3 4
3 5
3 6
3 7
4 4
4 5
4 6
4 7
5 5
5 6
5 7
6 6
6 7
7 7


In [13]:
print(J) #1, 2のみ

{(0, 0): 1.0, (0, 1): 1.0, (0, 2): 1.0, (0, 3): 1.0, (0, 4): 1.0, (0, 5): 1.0, (0, 6): 1.0, (0, 7): 1.0, (1, 1): 2.0, (1, 2): 1.0, (1, 3): 2.0, (1, 4): 1.0, (1, 5): 2.0, (1, 6): 1.0, (1, 7): 2.0, (2, 2): 1.0, (2, 3): 1.0, (2, 4): 1.0, (2, 5): 1.0, (2, 6): 1.0, (2, 7): 1.0, (3, 3): 2.0, (3, 4): 1.0, (3, 5): 2.0, (3, 6): 1.0, (3, 7): 2.0, (4, 4): 1.0, (4, 5): 1.0, (4, 6): 1.0, (4, 7): 1.0, (5, 5): 2.0, (5, 6): 1.0, (5, 7): 2.0, (6, 6): 1.0, (6, 7): 1.0, (7, 7): 2.0}


In [14]:
h #すべての値が0

{0: 0, 1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0}

In [15]:
sampler = neal.SimulatedAnnealingSampler()
response = sampler.sample_ising(h, J, num_reads=100)

In [20]:
response1 = sampler.sample_qubo(J, num_reads=10)

In [22]:
for sample in response1:
    print(sample)#0のみ

{0: 0, 1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0}
{0: 0, 1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0}
{0: 0, 1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0}
{0: 0, 1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0}
{0: 0, 1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0}
{0: 0, 1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0}
{0: 0, 1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0}
{0: 0, 1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0}
{0: 0, 1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0}
{0: 0, 1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0}


In [12]:
k=0
con1 = np.zeros(100)
con2 = np.zeros(100)
for sample in response:
    print(sample)
    for i in range(dim):
        con1[k] = con1[k]+w1[i]*sample[i]
        con2[k] = con2[k]+w2[i]*sample[i]
    k = k+1

{0: -1, 1: 1, 2: -1, 3: 1, 4: 1, 5: -1, 6: 1, 7: -1}
{0: 1, 1: -1, 2: 1, 3: 1, 4: -1, 5: -1, 6: -1, 7: 1}
{0: -1, 1: -1, 2: 1, 3: -1, 4: 1, 5: 1, 6: -1, 7: 1}
{0: -1, 1: 1, 2: -1, 3: 1, 4: 1, 5: -1, 6: 1, 7: -1}
{0: -1, 1: 1, 2: 1, 3: 1, 4: -1, 5: -1, 6: 1, 7: -1}
{0: 1, 1: -1, 2: -1, 3: 1, 4: -1, 5: 1, 6: 1, 7: -1}
{0: -1, 1: -1, 2: -1, 3: -1, 4: 1, 5: 1, 6: 1, 7: 1}
{0: 1, 1: 1, 2: -1, 3: 1, 4: 1, 5: -1, 6: -1, 7: -1}
{0: -1, 1: -1, 2: -1, 3: 1, 4: 1, 5: 1, 6: 1, 7: -1}
{0: 1, 1: -1, 2: -1, 3: 1, 4: 1, 5: -1, 6: -1, 7: 1}
{0: 1, 1: -1, 2: -1, 3: 1, 4: -1, 5: -1, 6: 1, 7: 1}
{0: -1, 1: -1, 2: 1, 3: 1, 4: -1, 5: -1, 6: 1, 7: 1}
{0: 1, 1: 1, 2: -1, 3: 1, 4: -1, 5: -1, 6: 1, 7: -1}
{0: 1, 1: 1, 2: -1, 3: 1, 4: -1, 5: -1, 6: 1, 7: -1}
{0: 1, 1: 1, 2: 1, 3: -1, 4: -1, 5: 1, 6: -1, 7: -1}
{0: -1, 1: -1, 2: 1, 3: -1, 4: 1, 5: 1, 6: -1, 7: 1}
{0: 1, 1: -1, 2: -1, 3: -1, 4: 1, 5: 1, 6: -1, 7: 1}
{0: 1, 1: 1, 2: 1, 3: 1, 4: -1, 5: -1, 6: -1, 7: -1}
{0: 1, 1: -1, 2: -1, 3: 1, 4: -1, 5: 1, 6: 1, 

In [13]:
print(con1) #和

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]


In [14]:
print(con2)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]


In [15]:
print(k)

100


In [14]:
!pip3 install pyqubo

  Running setup.py bdist_wheel for pyqubo ... done
  Stored in directory: /root/.cache/pip/wheels/77/b7/47/b989889699f788f4fecdc534bfddbb16df9a9a51f4e431b04d
Successfully built pyqubo


In [15]:
import pyqubo
Q = np.array([
       [ 1,  2, -1,  0],
       [ 0, -1, -2, -1],
       [ 0,  0, -2,  2],
       [ 0,  0,  0,  0]
  ])
x = pyqubo.Array.create('x', shape=(4), vartype='BINARY') 
xQx = x.dot(Q.dot(x))
xQx

((Binary(x[0])*((Binary(x[0])*Num(1))+(Binary(x[1])*Num(2))+(Binary(x[2])*Num(-1))+(Binary(x[3])*Num(0))))+(Binary(x[1])*((Binary(x[0])*Num(0))+(Binary(x[1])*Num(-1))+(Binary(x[2])*Num(-2))+(Binary(x[3])*Num(-1))))+(Binary(x[2])*((Binary(x[0])*Num(0))+(Binary(x[1])*Num(0))+(Binary(x[2])*Num(-2))+(Binary(x[3])*Num(2))))+(Binary(x[3])*((Binary(x[0])*Num(0))+(Binary(x[1])*Num(0))+(Binary(x[2])*Num(0))+(Binary(x[3])*Num(0)))))