## 課題
- [QUBOとその解の探索](https://tsudalab.kibe.la/@kitai/1223)

In [2]:
import numpy as np

In [3]:
def f(x):
    '''
    x: 長さ4で要素に0, 1のみを持つNumpy行列
    '''
    assert np.all((x == 0) | (x == 1))
    Q = np.array([
    [ 1,  2, -1,  0],
    [ 0, -1, -2, -1],
    [ 0,  0, -2,  2],
    [ 0,  0,  0,  0]
    ])
    return np.dot(x.T, np.dot(Q, x))

In [4]:
def allX(n):
    '''
    長さnの0,1ベクトルの全パターンを列挙して2次元のNumpy行列として返す。
    '''
    Xs = np.arange(2**n).reshape((-1,1))
    mask = 1 << np.arange(n-1, -1, -1).reshape((1,-1))
    return (Xs & mask) / mask

## 課題1

In [98]:
for each_x in allX(4):
    print(each_x, f(each_x))

[0. 0. 0. 0.] 0.0
[0. 0. 0. 1.] 0.0
[0. 0. 1. 0.] -2.0
[0. 0. 1. 1.] 0.0
[0. 1. 0. 0.] -1.0
[0. 1. 0. 1.] -2.0
[0. 1. 1. 0.] -5.0
[0. 1. 1. 1.] -4.0
[1. 0. 0. 0.] 1.0
[1. 0. 0. 1.] 1.0
[1. 0. 1. 0.] -2.0
[1. 0. 1. 1.] 0.0
[1. 1. 0. 0.] 2.0
[1. 1. 0. 1.] 1.0
[1. 1. 1. 0.] -3.0
[1. 1. 1. 1.] -2.0


## 課題2

In [ ]:
def f2(x):
    return f(x) + 2*(np.sum(x) - 1)**2

In [104]:
def f2(x):
    '''
    x: 長さ4で、要素は3つが1で残り1つは0になるNumpy行列
    '''
    if np.all((x==0)|(x==1)) and np.sum(x) == 3:
        Q = np.array([
        [ 1, 2, -1, 0],
        [ 0, -1, -2, -1],
        [ 0, 0, -2, 2],
        [ 0, 0, 0, 0]
        ])
        return np.dot(x.T, np.dot(Q, x))

In [107]:
for each_x in allX(4):
    if f2(each_x) != None:
        print(each_x, f2(each_x))

[0. 1. 1. 1.] -4.0
[1. 0. 1. 1.] 0.0
[1. 1. 0. 1.] 1.0
[1. 1. 1. 0.] -3.0


## 課題3

In [84]:
from pyqubo import Array, Binary, solve_qubo

In [85]:
x = Array.create('x', shape=4, vartype='BINARY')
H = x[0] - x[1] -2*x[2] + 2*x[0]*x[1] - x[0]*x[2] - 2*x[1]*x[2] -x[1]*x[3] + 2*x[2]*x[3]
model = H.compile()
qubo, offset = model.to_qubo()

In [87]:
#PyQUBOによるSA
raw_solution = solve_qubo(qubo)

# 得られた結果をデコードする
decoded_solution, broken, energy = model.decode_solution(raw_solution, vartype="BINARY")
decoded_solution['x'] #{0: 0, 1: 1, 2: 1, 3: 0}

{0: 0, 1: 1, 2: 1, 3: 0}

$H$

$= f(x) +2*g(x)**2$

$= x[0] - x[1] -2*x[2] + 2*x[0]*x[1] - x[0]*x[2] - 2*x[1]*x[2] -x[1]*x[3] + 2*x[2]*x[3]　- (2-2*x[0]-2*x[1]-2*x[2]+4*x[0]*x[1]+4*x[1]*x[2] + 4*x[0]*x[2])$
$= -x[0] - 3*x[1] - 4*x[2] + 2 - 6*x[0]*x[1] + 3*x[0]* x[2] +2*x[1]*x[2]- x[1]*x[3] + 2*x[2]*x[3]$

In [94]:
x = Array.create('x', shape=4, vartype='BINARY')
H = -x[0]-3*x[1]-4*x[2]+2-6*x[0]*x[1]+3*x[0]*x[2]+2*x[1]*x[2]-x[1]*x[3]+2*x[2]*x[3]
model = H.compile()
qubo, offset = model.to_qubo()

In [95]:
#PyQUBOによるSA
raw_solution = solve_qubo(qubo)

# 得られた結果をデコードする
decoded_solution, broken, energy = model.decode_solution(raw_solution, vartype="BINARY")
decoded_solution['x']

{0: 1, 1: 1, 2: 0, 3: 1}