interaction informaionは正負両方取りうる
相互情報量mutual infomationは正のみとる

# Thesis
Discovering pair-wise genetic interactions: An infromation theory-based approach


- 修飾相互作用(modifier interaction)と合成相互作用(synthetic interaction)に対し利用する、ID(interation distance)という相互作用情報(interaction infomation)の概念を拡張した距離を開発した

- 近年遺伝子の相互作用の分析に非常に有効だとして使われている相互作用情報を利用した指標を開発した

## Terms
- interaction ingormation $ID ≡ d(X1;X2・Y) = d(X1;X2) - d(X1; X2|Y)$
- mutual information $I(X1; X2)$
- conditional information $H(Y|Xi)$...measure of dependence of $Y$ on a single variable $Xi$, 条件付きエントロピー
- joint entropy $H(X, Y$)...結合エントロピー
- sign convention...a choice of the physical significance of signs (plus or minus) for a set of quantities, in a case where the choice of sign is arbitrary. 

<br/>
$\begin{align}
I(X, Y)& = H(X) - H(X|Y)\\
& = H(Y) - H(Y|X)\\
& = H(X) + H(Y) - H(X, Y)\\
\end{align}
$

$H(X|Y) = H(X, Y) - H(Y) $

$\begin{align}
ID  &= \frac{I(X1, X2)}{max[H(X1), H(X2)]} +  \frac{I(X1, X2 | Y)}{max[H(X1|Y), H(X2|Y)]}\\
& = \frac{H(X1) + H(X2) - H(X1, X2)}{max[H(X1), H(X2)]}
+ \frac{H(X1, Y) + H(X2, Y) - H(X1, X2, Y) - H(Y)}{max[H(X1, Y) - H(Y), H(X2, Y) - H(Y)]}\\
\end{align}
$

<br/>
<img src='20190809223738.png' width=50%>

- conditional mutual information $I(x; y |z$)...the expected value of the mutual information of two random variables given the value of a third

$\begin{align}
I(X;Y|Z) &= H(X, Z) + H(Y, Z) - H(X, Y, Z) - H(Z)\\
& = H(X|Z) - H(X|Y, Z)\\
& = H(X|Z) - H(Y|Z) - H(X, Y|Z)\\
& = H(Z|X) + H(X) + H(Z|Y) + H(Y) - H(Z|X, Y) - H(X, Y)\\
& = I(X;Y) + H(Z|X) + H(Z|Y) - H(Z|X, Y) - H(Z)\\
\end{align}$

<img src='20190810150512.png' width=50%>

In [1]:
#import pandas as pd
#df = pd.read_csv('sample.csv', index_col=0)
#df

In [2]:
import numpy as np

a = np.loadtxt('sample.csv', delimiter=',', dtype='int64',
               skiprows=1, usecols=[1, 2, 3, 4, 5])

print(a) #TF1, 2, 3, 4, exの計5要素（列）。計15遺伝子サンプル（行）

[[1 1 1 0 1]
 [1 1 1 0 1]
 [1 0 0 1 0]
 [0 0 0 0 0]
 [1 1 1 0 1]
 [1 0 0 0 0]
 [1 1 1 1 1]
 [0 0 0 0 1]
 [0 1 0 1 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 1 0]
 [0 0 0 1 1]
 [1 1 1 0 1]
 [0 0 0 0 0]]


In [3]:
a_dic = {}
for i in range(10):
    for j in range(20):
        a_dic[str(i), str(j)] = [i,j]

# 内包表記バージョン
#a_dic = {str(i)str(j) : [i, j] for i in range(10) for j in range(20)}

a_dic["1", "2"]
# [1, 2]

[1, 2]

In [4]:
b = [0]*2**3
print(b)

c=[3]
print(c[-1])

[0, 0, 0, 0, 0, 0, 0, 0]
3


In [5]:
TFe1_list = [['TF1'], ['TF2'], ['TF3'], ['TF4'], ['ex']]
a1_list = []
for j in range(5):
    TFe =[]
    a1_list.append(TFe) #aの列固定、a2_listの行固定
    for k in range(2): #a2_listの列固定
            TFe.append(0)
            for i in range(15): #aの行固定
                if a[i][j]==k:
                    TFe[-1] +=1
"""
[[TF1が0, 1],
[TF2が0, 1], 
[TF3が0, 1], 
[TF4が0 ,1], 
[exが0, 1]]
"""                    
print(a1_list)
print(len(a1_list))
print(len(a1_list[0]))
print(TFe1_list[0][0])

[[8, 7], [9, 6], [9, 6], [9, 6], [8, 7]]
5
2
TF1


In [6]:
TFe2_list = []
a2_list = []
for j in range(5):
    for k in range(5):
        if j < k:
            TFe2_list.append([TFe1_list[j], TFe1_list[k]])
            TFe =[]
            a2_list.append(TFe) #aの列固定、a2_listの行固定
            for l in range(2):
                for m in range(2): #a2_listの列固定
                    TFe.append(0)
                    for i in range(15): #aの行固定
                        if a[i][j]==l and a[i][k]==m:
                            TFe[-1] +=1

"""
00 ,01, 10, 11(2*2=4列）両者の表現型
[[] TF12
[] TF13
[] TF14
[] TF1ex
[] TF23
[] TF24
[] TF2ex
[] TF34
[] TF3ex
[]] TF4ex（5*4/2=10行）

[[7, 1, 2, 5], [7, 1, 2, 5], [4, 4, 5, 2], [6, 2, 2, 5], [8, 1, 1, 5], [5, 4, 4, 2], [7, 2, 1, 5], [4, 5, 5, 1], [7, 2, 1, 5], [4, 5, 4, 2]]

"""
print(a2_list)
print(len(a2_list))
print(len(a2_list[0]))
print(TFe2_list[0])
print(TFe2_list[0][0][0], TFe2_list[0][1][0])

[[7, 1, 2, 5], [7, 1, 2, 5], [4, 4, 5, 2], [6, 2, 2, 5], [8, 1, 1, 5], [5, 4, 4, 2], [7, 2, 1, 5], [4, 5, 5, 1], [7, 2, 1, 5], [4, 5, 4, 2]]
10
4
[['TF1'], ['TF2']]
TF1 TF2


In [7]:
TFe3_list = []
a3_list = []
for j in range(5):
    for k in range(5):
        for l in range(5):
            if j < k and k < l:
                TFe3_list.append([TFe1_list[j], TFe1_list[k], TFe1_list[l]])
                TFe =[]
                a3_list.append(TFe) #aの列固定、a2_listの行固定
                for m in range(2):
                    for n in range(2): #a2_listの列固定
                        for o in range(2):
                            TFe.append(0)
                            for i in range(15): #aの行固定
                                if a[i][j]==m and a[i][k]==n and a[i][l]==o:
                                    TFe[-1] +=1

'''
000, 001, 010, 011, 100, 101, 110, 111(2**3列) 三者の表現型
[[] TF123
[] TF124
[] TF12ex
[] TF134
[] TF13ex
[] TF14ex
[] TF234
[] TF23ex
[] TF24ex
[]] TF34ex (5C3=10行)

 [[6, 1, 1, 0, 2, 0, 0, 5], [4, 3, 0, 1, 1, 1, 4, 1], [5, 2, 1, 0, 2, 0, 0, 5], [3, 4, 1, 0, 1, 1, 4, 1], [5, 2, 1, 0, 2, 0, 0, 5]
 , [3, 1, 3, 1, 1, 4, 1, 1], [4, 4, 1, 0, 0, 1, 4, 1], [6, 2, 1, 0, 1, 0, 0, 5], [4, 1, 3, 1, 0, 4, 1, 1], [3, 1, 4, 1, 1, 4, 0, 1]]
'''                
print(a3_list)
print(len(a3_list))
print(len(a3_list[0]))
print(TFe3_list)
print(TFe3_list[0][0][0], TFe3_list[0][1][0], TFe3_list[0][2][0])

[[6, 1, 1, 0, 2, 0, 0, 5], [4, 3, 0, 1, 1, 1, 4, 1], [5, 2, 1, 0, 2, 0, 0, 5], [3, 4, 1, 0, 1, 1, 4, 1], [5, 2, 1, 0, 2, 0, 0, 5], [3, 1, 3, 1, 1, 4, 1, 1], [4, 4, 1, 0, 0, 1, 4, 1], [6, 2, 1, 0, 1, 0, 0, 5], [4, 1, 3, 1, 0, 4, 1, 1], [3, 1, 4, 1, 1, 4, 0, 1]]
10
8
[[['TF1'], ['TF2'], ['TF3']], [['TF1'], ['TF2'], ['TF4']], [['TF1'], ['TF2'], ['ex']], [['TF1'], ['TF3'], ['TF4']], [['TF1'], ['TF3'], ['ex']], [['TF1'], ['TF4'], ['ex']], [['TF2'], ['TF3'], ['TF4']], [['TF2'], ['TF3'], ['ex']], [['TF2'], ['TF4'], ['ex']], [['TF3'], ['TF4'], ['ex']]]
TF1 TF2 TF3


In [8]:
TFe4_list = []
a4_list = []
for j in range(5):
    for k in range(5):
        for l in range(5):
            for m in range(5):
                if j < k and k < l and l < m:
                    TFe4_list.append([TFe1_list[j], TFe1_list[k], TFe1_list[l], TFe1_list[m]])
                    TFe =[]
                    a4_list.append(TFe) #aの列固定、a2_listの行固定
                    for n in range(2):
                        for o in range(2): #a2_listの列固定
                            for p in range(2):
                                for q in range(2):
                                    TFe.append(0)
                                    for i in range(15): #aの行固定
                                        if a[i][j]==n and a[i][k]==o and a[i][l]==p and a[i][m]==q:
                                            TFe[-1] +=1

'''
0000, 0001, 0010, 0011, 0100, 0101, 0110, 0111, 1000, 1001, 1010, 1011, 1100, 1101, 1110, 1111(2**4=16列) 四者の表現型
[[] TF1234
[] TF123ex
[] TF124ex
[] TF134ex
[]] TF234ex (5行)

 [[3, 3, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 4, 1], [4, 2, 1, 0, 1, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 5], [3, 1, 2, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 4, 0, 1]
 , [2, 1, 3, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 4, 0, 1], [3, 1, 3, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 4, 0, 1]]
'''                
print(a4_list)
print(len(a4_list))
print(len(a4_list[0]))
print(TFe4_list, len(TFe4_list))
print(TFe4_list[0][0][0], TFe4_list[0][1][0], TFe4_list[0][2][0], TFe4_list[0][3][0])

[[3, 3, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 4, 1], [4, 2, 1, 0, 1, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 5], [3, 1, 2, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 4, 0, 1], [2, 1, 3, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 4, 0, 1], [3, 1, 3, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 4, 0, 1]]
5
16
[[['TF1'], ['TF2'], ['TF3'], ['TF4']], [['TF1'], ['TF2'], ['TF3'], ['ex']], [['TF1'], ['TF2'], ['TF4'], ['ex']], [['TF1'], ['TF3'], ['TF4'], ['ex']], [['TF2'], ['TF3'], ['TF4'], ['ex']]] 5
TF1 TF2 TF3 TF4


In [9]:
TFe5_list = [[['TF1'], ['TF2'], ['TF3'], ['TF4'], ['ex']]]
a5_list = []
TFe =[]
a5_list.append(TFe) #aの列固定、a2_listの行固定
for l in range(2):
    for m in range(2): #a2_listの列固定
        for n in range(2):
            for o in range(2):
                for p in range(2):
                    TFe.append(0)
                    for i in range(15): #aの行固定
                        if a[i][0]==m and a[i][1]==n and a[i][2]==o and a[i][2]==p and a[i][4]==q:
                            TFe[-1] +=1
                            
print(a5_list)  
print(len(a5_list)) #1
print(len(a5_list[0])) #2**5
print(TFe5_list, len(TFe5_list))
print(TFe5_list[0][0][0], TFe5_list[0][1][0], TFe5_list[0][2][0], TFe5_list[0][3][0], TFe5_list[0][4][0])

[[2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5]]
1
32
[[['TF1'], ['TF2'], ['TF3'], ['TF4'], ['ex']]] 1
TF1 TF2 TF3 TF4 ex


In [10]:
from scipy.stats import entropy #あるできごと（事象）が起きた際、それがどれほど起こりにくいかを表す尺度
# 起こりにくい事象（＝生起確率が低い事象）の情報量ほど、値が大きい。

print(entropy([0, 100, 10], base=2)) # 1.0

0.43949698692151334


### 例）TF1, 2, ex

- $X1 = TF1$
- $X2 = TF2$
- $Y = ex$

とする

必要な数値は
- $H(TF1)$
- $H(TF2)$
- $H(ex)$
- $H(TF1, TF2)$
- $H(X1, ex)$
- $H(X2, ex)$
- $H(X1, X2, ex)$

の7つ

In [11]:
# TFe1_list = [['TF1'], ['TF2'], ['TF3'], ['TF4'], ['ex']]
print(TFe1_list[0])
a1_list[TFe1_list[0].index("TF1")]

['TF1']


[8, 7]

In [12]:
H1 = {}
for r in TFe1_list:
    H1[r[0]] = entropy(a1_list[TFe1_list.index(r)], base=2)
    
print(H1)
print(H1['TF1'])
print(entropy([8, 7], base=2)) #TF1の0, 1の出方の均等具合 = H1["TF1"]

{'TF1': 0.9967916319816367, 'TF2': 0.9709505944546688, 'TF3': 0.9709505944546688, 'TF4': 0.9709505944546688, 'ex': 0.9967916319816367}
0.9967916319816367
0.9967916319816367


In [13]:
s=TFe2_list[2]

print(TFe2_list[2])
print(s)

print(TFe2_list[2][0])
print(s[0])
print(s[0][0], s[1][0] )

print(a2_list[TFe2_list.index(TFe2_list[2])])
print(a2_list[TFe2_list.index(s)])

[['TF1'], ['TF4']]
[['TF1'], ['TF4']]
['TF1']
['TF1']
TF1 TF4
[4, 4, 5, 2]
[4, 4, 5, 2]


In [14]:
H2 = {}
for r in TFe2_list:
    H2[r[0][0], r[1][0]] = entropy(a2_list[TFe2_list.index(r)], base=2)

print(H2['TF1', 'TF2'])
print(entropy([7, 1, 2, 5], base=2)) #TF1, TF2の0, 1の出方の均等具合 = H2["TF1, TF2"]

1.6894822670191825
1.6894822670191825


In [15]:
#TFe3_list = ["TF1, TF2, TF3", "TF1, TF2, TF4", "TF1, TF2, ex", "TF1, TF3, TF4", "TF1, TF3, ex", "TF1, TF4, ex", "TF2, TF3, TF4", "TF2, TF3, ex", "TF2, TF4, ex", "TF3, TF4, ex"]
#print(len(TFe3_list))

H3 = {}
for r in TFe3_list:
    H3[r[0][0], r[1][0], r[2][0]] = entropy(a3_list[TFe3_list.index(r)], base=2)
    
print(H3['TF1', 'TF2', 'TF3'])
print(entropy([6, 1, 1, 0, 2, 0, 0, 5], base=2)) #TF1, TF2, TF3の0, 1の出方の均等具合 = H3["TF1, TF2, TF3"]

1.965596230357602
1.965596230357602


In [16]:
#TFe4_list = ["TF1, TF2, TF3, TF4", "TF1, TF2, TF3, ex", "TF1, TF2, TF4, ex", "TF1, TF3, TF4, ex", "TF2, TF3, TF4, ex"]
#print(len(TFe4_list))

H4 = {}
for r in TFe4_list:
    H4[r[0][0], r[1][0], r[2][0], r[3][0]] = entropy(a4_list[TFe4_list.index(r)], base=2)
    
print(H4['TF1', 'TF2', 'TF3', 'TF4'])
print(entropy([3, 3, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 4, 1], base=2)) 
#TF1, TF2, TF3, TF4の0, 1の出方の均等具合 = H3["TF1, TF2, TF3, TF4"]

2.739572261986723
2.739572261986723


$\begin{align}
ID &= \frac{I(X1, X2)}{max[H(X1), H(X2)]} +  \frac{I(X1, X2 | Y)}{max[H(X1|Y), H(X2|Y)]}\\
& = \frac{H(X1) + H(X2) - H(X1, X2)}{max[H(X1), H(X2)]}
+ \frac{H(X1, Y) + H(X2, Y) - H(X1, X2, Y) - H(Y)}{max[H(X1, Y) - H(Y), H(X2, Y) - H(Y)]}\\
\end{align}
$

In [17]:
#print(max([10, 20, 30, 20, 5, 3]))

In [18]:
def ID(X1, X2, Y):
    ID1 = (H1[X1] + H1[X2] - H2[X1, X2])/max([H1[X1], H1[X2]]) 
    ID2 = (H2[X1, Y] + H2[X2, Y] - H3[X1, X2, Y] - H1[Y])/max([H2[X1, Y] - H1[Y], H2[X2, Y] - H1[Y]])
    print(ID1 + ID2)

In [19]:
ID('TF1', 'TF2', 'ex')

0.797044938485054


In [20]:
ID('TF1', 'TF3', 'ex')

0.797044938485054


### References
リストへの要素の追加と別のリストとの結合 https://www.javadrive.jp/python/list/index6.html <br/>
最大値最小値の取得 https://www.python-izm.com/advanced/min_max/<br/>
Conditional mutual information https://en.wikipedia.org/wiki/Conditional_mutual_information